apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\jayla\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  labels:
    io.kompose.service: swagger
  name: swagger
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: swagger
status:
  loadBalancer: {}
