apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\jayla\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  labels:
    io.kompose.service: swagger
  name: swagger
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: swagger
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\jayla\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      labels:
        io.kompose.service: swagger
    spec:
      containers:
        - env:
            - name: API_URL
              value: http://127.0.0.1:3000/
          image: swaggerapi/swagger-ui
          name: swagger
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
